services:
  dev-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: waker-dev
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  test-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: waker-test
    volumes:
      - test_db_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - dev-db
      - test-db

volumes:
  dev_db_data:
  test_db_data:
